name: CI

on: [push, pull_request]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install and test backend
        run: |
          cd backend
          npm install
          npm run test
